# Site settings
title: Vedant Kalbande
general_email: vedantuk11@gmail.com
academic_email: vedantk@iitb.ac.in

description: > # this means to ignore newlines until "baseurl:"
  Hi, I am Vedant, a computer science enthusiast.

baseurl: "/academic-portfolio" # the subpath of your site, e.g. /blog/

url: "https://ys1998.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: VedantK11
linkedin_username: vedant-kalbande-80a5a6279
facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
